### PR TITLE
Fix Map issues and reintroduce responsive bars

### PR DESCRIPTION
**Pull request by Inkering**
Had a hiccup with the map and the recursive bars. This slight adjustment should fix it!

### CODE REVIEW

**Review by anushadatar — APPROVED** [review]
LGTM if this works as expected (lmk if it would be helpful if I tested it). One thing I'd propose if you weren't already planning to do this is that this is a good candidate for a squash merge to keep the git history clean.

**Comment by Inkering** [comment]
@anushadatar Would love it if you tested. I'm also not great at squashing so if it looks good to you upon testing, can you perform that?

**Review by davidt315 — APPROVED** [review]

**Comment by davidt315** [comment]
Another thing I noticed with the map on the iOS app was the popup window takes up the whole screen if you click a marker. Not sure if this helps with that as well

**Comment by Inkering** [comment]
yup! That was what the change was for.

**Comment by anushadatar** [comment]
image
Here's what it looks like on my machine on the web client, I'm not sure if this is quite the desired behavior.

**Comment by anushadatar** [comment]
Completing merge as discussed

**Pull request merged**
