### PR TITLE
Stage two revere sensors

### PR DESCRIPTION
**Pull request by Inkering**
Still checking some things here, but getting this started. The two revere sensors show up correctly on my build, but more checking needed.

### CODE REVIEW

**Comment by Inkering** [comment]
SN000-114 is not showing co2, o3, no2, or no, but also doesn't show show fields via QuantAQ, so I'm assuming that it isn't an issue on our end...

**Comment by Inkering** [comment]
This should be merge-able at this point! Verified the locations with Scott

**Review by davidt315 — APPROVED** [review]
looks good!

**Comment by Inkering** [comment]
Also that sensor that I mentioned above is now working, was an issue on the sensor-side or a short glitch.

**Review by anushadatar — APPROVED** [review]
lgtm

**Pull request merged**
