### PR TITLE
Faq coming soon

### PR DESCRIPTION
**Pull request by Inkering**
Makes a route and page for an in progress knowledge base.
Screen Shot 2020-11-24 at 5 30 47 PM

### CODE REVIEW

**Review by ntchirkova — APPROVED** [review]
Looks good to me, not sure if FAQ or faq is looks better for a URL but that can be changed if needed.

**Comment by Inkering** [comment]
Not sure why the check failed... no problem on my end. ¯\_(ツ)_/¯

**Comment by ntchirkova** [comment]
Actually seems like it is failing to compile, some issue with a variable not being used :/

**Review by ntchirkova — APPROVED** [review]
Nice, I think this should clear up the issue

**Pull request merged**
